[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[settings.github]
credential_command = "gh auth token"
github_attestations = false

[tools]
"llama.cpp" = { version = "latest", version_prefix = "b" }
"glow" = "latest"
